version: "3"
services:
  dashboard:
    container_name: front
    build:
      context: "./dashboard"
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  back-end:
    container_name: back-end
    build:
      context: "./hello-world"
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    networks: 
      - back-tier

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    networks: 
      - back-tier
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
    networks: 
      - back-tier

volumes:
  mysql: ~

networks: 
  back-tier: